const DRIVES_DATA = {
  '01': {
    title: 'Foundations',
    marker: '1ST & 10',
    description: 'The threat model, identity, patching, zero trust, and the CIA triad — as decision tools, not textbook definitions.',
    summary: 'Core concepts that make everything else make sense. Zero trust isn't about products; identity is your perimeter; patching is the only thing that actually works.',
    lessons: [
      { number: '01', title: 'The Threat Model Nobody Teaches', marker: '1ST & 10', time: '18 MIN', state: 'done' },
      { number: '02', title: 'Identity Is the Perimeter', marker: '1ST & 10', time: '16 MIN', state: 'done' },
      { number: '03', title: 'Patching: The Only Thing That Actually Works', marker: '1ST & 10', time: '14 MIN', state: 'current' },
      { number: '04', title: 'Zero Trust Decoded', marker: '2ND & 7', time: '20 MIN', state: 'locked' },
      { number: '05', title: 'CIA Triad: Confidentiality, Integrity, Availability', marker: '1ST & 10', time: '12 MIN', state: 'locked' },
    ],
  },
  '03': {
    title: 'Cloud & Modern Surface',
    marker: '2ND & 7',
    description: 'Cloud misconfigurations, MFA fatigue, shadow IT, SaaS sprawl, API basics, and container security.',
    summary: 'Your infrastructure is no longer four walls. This drive covers identity in the cloud, the attack surface you can't see, and why containers aren't the answer to everything.',
    lessons: [
      { number: '13', title: 'Cloud Misconfigurations 101', marker: '1ST & 10', time: '17 MIN', state: 'done' },
      { number: '14', title: 'MFA Fatigue: When Your Best Defense Backfires', marker: '2ND & 7', time: '19 MIN', state: 'done' },
      { number: '15', title: 'Shadow IT and SaaS Sprawl', marker: '2ND & 7', time: '15 MIN', state: 'locked' },
      { number: '16', title: 'API Security Basics', marker: '2ND & 7', time: '16 MIN', state: 'locked' },
      { number: '17', title: 'Container Security Without the Hype', marker: '3RD & LONG', time: '21 MIN', state: 'locked' },
      { number: '18', title: 'Kubernetes: What You Actually Need to Know', marker: '3RD & LONG', time: '20 MIN', state: 'locked' },
    ],
  },
  '04': {
    title: 'Practical Defense & Career',
    marker: '2ND & 7',
    description: 'Backup strategy, vendor risk, incident response basics, talking to leadership, and certs worth pursuing.',
    summary: 'Shift from theory to action. How to back up without fail, navigate the vendor maze, handle incidents on your own, and build a career without chasing every certification.',
    lessons: [
      { number: '19', title: 'The Backup Strategy That Actually Works', marker: '1ST & 10', time: '18 MIN', state: 'done' },
      { number: '20', title: 'Vendor Risk: Buying Security Isn't Enough', marker: '2ND & 7', time: '16 MIN', state: 'locked' },
      { number: '21', title: 'Incident Response Without a Team', marker: '2ND & 7', time: '22 MIN', state: 'locked' },
      { number: '22', title: 'Talking to Leadership About Security', marker: '2ND & 7', time: '14 MIN', state: 'locked' },
      { number: '23', title: 'Security Certifications: Which Ones Matter', marker: '3RD & LONG', time: '19 MIN', state: 'locked' },
    ],
  },
  '05': {
    title: 'The Human Element',
    marker: '3RD & LONG',
    description: 'Social engineering, building a security culture people don't hate, insider threats, and phishing sims done right.',
    summary: 'Most breaches start with a person. This drive covers social engineering tactics, how to build a culture that doesn't resent security, recognizing insider risk, and running phishing campaigns that teach instead of punish.',
    lessons: [
      { number: '24', title: 'Social Engineering: The Classics and New Tactics', marker: '2ND & 7', time: '17 MIN', state: 'locked' },
      { number: '25', title: 'Building a Security Culture People Don't Hate', marker: '3RD & LONG', time: '23 MIN', state: 'locked' },
      { number: '26', title: 'Insider Threats: Recognition and Response', marker: '3RD & LONG', time: '18 MIN', state: 'locked' },
      { number: '27', title: 'Phishing Simulations Done Right', marker: '2ND & 7', time: '15 MIN', state: 'locked' },
    ],
  },
  '06': {
    title: 'Compliance & Governance',
    marker: '3RD & LONG',
    description: 'Compliance isn't security, frameworks decoded (NIST, CIS, ISO), and surviving audit season.',
    summary: 'Compliance is a tool, not the goal. Understand NIST, CIS, and ISO without drowning in documentation. Map your work to frameworks and survive audits without losing your mind.',
    lessons: [
      { number: '28', title: 'Compliance vs. Security: Why They're Different', marker: '2ND & 7', time: '14 MIN', state: 'locked' },
      { number: '29', title: 'NIST, CIS, ISO: Which Framework When', marker: '3RD & LONG', time: '21 MIN', state: 'locked' },
      { number: '30', title: 'Surviving Audit Season', marker: '3RD & LONG', time: '16 MIN', state: 'locked' },
    ],
  },
};
